<template>
  <div class="ai-container">
    <el-card class="top-nav-card" shadow="never">
      <div class="header-content">
        <div class="title-section">
          <el-icon class="ai-icon"><Switch /></el-icon>
          <span class="title">AI 用例转换 (Natural Language ➔ Code)</span>
        </div>
        <div class="target-select-section">
          <span class="label">目标自动化框架：</span>
          <el-radio-group v-model="targetFramework" size="small">
            <el-radio-button label="Intentra" />
            <el-radio-button label="Appium (Python)" />
            <el-radio-button label="Playwright (JS)" />
            <el-radio-button label="Airtest" />
          </el-radio-group>
        </div>
      </div>
    </el-card>

    <div class="convert-layout">
      <!-- 源代码区 -->
      <div class="side-panel">
        <el-card class="panel-card" shadow="hover">
          <template #header>
            <div class="card-header">
              <span>原始自然语言步骤</span>
              <el-button type="primary" link @click="pasteExample">示例</el-button>
            </div>
          </template>
          <el-input
            v-model="sourceCode"
            type="textarea"
            :rows="20"
            placeholder="请粘贴您的手工用例步骤，例如：
1. 打开美图秀秀APP。
2. 点击首页正上方的搜索框。
3. 输入关键词“修图”。
4. 点击键盘搜索键。"
            class="code-input"
          />
        </el-card>
      </div>

      <!-- 中心转换按钮 -->
      <div class="center-action">
        <el-button 
          type="primary" 
          circle 
          class="convert-circle-btn" 
          :loading="converting"
          @click="handleConvert"
        >
          <el-icon size="24"><Right /></el-icon>
        </el-button>
        <p class="convert-text">AI 转换</p>
      </div>

      <!-- 目标代码区 -->
      <div class="side-panel">
        <el-card class="panel-card" shadow="hover">
          <template #header>
            <div class="card-header">
              <span>生成的自动化代码 ({{ targetFramework }})</span>
              <el-button v-if="convertedCode" type="info" size="small" link @click="copyCode">复制</el-button>
            </div>
          </template>
          <div class="code-output-container">
            <el-input
              v-if="convertedCode"
              v-model="convertedCode"
              type="textarea"
              :rows="20"
              readonly
              class="code-output"
            />
            <div v-else class="empty-code">
              等待点击转换...
            </div>
          </div>
        </el-card>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { ElMessage } from 'element-plus';
import { Switch, Right } from '@element-plus/icons-vue';

const targetFramework = ref('Intentra');
const sourceCode = ref('');
const convertedCode = ref('');
const converting = ref(false);

const pasteExample = () => {
  sourceCode.value = `1. 进入个人中心页面
2. 点击“我的订单”
3. 在订单列表中搜索“2026”
4. 点击第一个订单进入详情
5. 验证是否存在“待评价”状态`;
};

const handleConvert = () => {
  if (!sourceCode.value.trim()) {
    return ElMessage.warning('请先输入或粘贴原始步骤');
  }
  
  converting.value = true;
  
  // 模拟 AI 转换逻辑
  setTimeout(() => {
    if (targetFramework.value === 'Intentra') {
      convertedCode.value = `// Generated by Intentra AI
进入页面 "个人中心"
点击文本 "我的订单"
输入框输入 "2026"
点击列表元素 [0]
断言 文本存在 "待评价"`;
    } else {
      convertedCode.value = `# Generated by Appium AI
driver.find_element(by=By.NAME, value="个人中心").click()
driver.find_element(by=By.NAME, value="我的订单").click()
search_box = driver.find_element(by=By.ID, value="order_search")
search_box.send_keys("2026")
driver.keyevent(66) # Enter
assert "待评价" in driver.page_source`;
    }
    
    converting.value = false;
    ElMessage.success('用例转换完成！');
  }, 1000);
};

const copyCode = () => {
  navigator.clipboard.writeText(convertedCode.value);
  ElMessage.success('代码已复制');
};
</script>

<style scoped>
.ai-container {
  padding: 16px;
  background-color: #f0f2f5;
  min-height: calc(100vh - 84px);
}

.top-nav-card {
  margin-bottom: 20px;
  border-radius: 12px;
}

.header-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.title-section {
  display: flex;
  align-items: center;
  gap: 12px;
}

.ai-icon {
  font-size: 24px;
  color: #67c23a;
}

.title {
  font-size: 18px;
  font-weight: 600;
  color: #303133;
}

.convert-layout {
  display: flex;
  align-items: flex-start;
  gap: 15px;
}

.side-panel {
  flex: 1;
}

.panel-card {
  border-radius: 12px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-weight: 600;
}

.center-action {
  width: 100px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding-top: 150px;
}

.convert-circle-btn {
  width: 60px !important;
  height: 60px !important;
  box-shadow: 0 4px 12px rgba(64, 158, 255, 0.4);
}

.convert-text {
  margin-top: 10px;
  font-size: 12px;
  color: #909399;
  font-weight: 600;
}

.code-input :deep(.el-textarea__inner) {
  font-family: 'Fira Code', 'Monaco', monospace;
  font-size: 13px;
  background-color: #fafafa;
}

.code-output-container {
  min-height: 400px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.code-output :deep(.el-textarea__inner) {
  font-family: 'Fira Code', 'Monaco', monospace;
  font-size: 13px;
  background-color: #282c34;
  color: #abb2bf;
}

.empty-code {
  color: #c0c4cc;
  font-style: italic;
}
</style>
